# Generated by Django 3.2.16 on 2023-01-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name']},
        ),
    ]
