# Generated by Django 3.2.16 on 2023-01-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_tagrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagRecipe',
        ),
    ]
