# Generated by Django 3.2.16 on 2023-01-23 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230123_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientnumber',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
