# Generated by Django 3.2.16 on 2023-01-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_tagrecipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientnumber',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='ingredient_number'),
        ),
    ]
